openapi: 3.0.1
info:
  description: Bran's Auth API
  title: API for AuthApplication
  version: "1.0"
servers:
- url: /
tags:
- description: Sign out a user
  name: Signout
- description: Send an email verification mail with OTP
  name: Send email verification mail
- description: "Update user details, requires OTP verification"
  name: Update user details
- description: Authenticate a user
  name: Authenticate
- description: Refresh a user's jwt token
  name: Refresh-token
- description: Register a new user
  name: Register
- description: Send an email verification mail with OTP and custom message
  name: Send custom email verification
- description: Validate an email verification OTP
  name: Validate email verification
paths:
  /api/v1/auth/authenticated/logout:
    post:
      operationId: signout
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/SignoutRequest'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AuthResponse'
          description: Default response
      security:
      - Authentication: []
      tags:
      - Signout
  /api/v1/auth/authenticated/send-email-verification-mail:
    post:
      operationId: sendVerificationEmail
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OtpRequestResponse'
          description: Default response
      security:
      - Authentication: []
      tags:
      - Send email verification mail
  /api/v1/auth/authenticated/update-user-details:
    post:
      operationId: updateUserDetails
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/UserDetailsUpdateRequest'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AuthResponse'
          description: Default response
      security:
      - Authentication: []
      tags:
      - Update user details
  /api/v1/auth/public/authenticate:
    post:
      operationId: authenticate
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/SigninRequest'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AuthResponse'
          description: Default response
      tags:
      - Authenticate
  /api/v1/auth/public/refresh-token:
    post:
      operationId: refeshToken
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AuthResponse'
          description: Default response
      tags:
      - Refresh-token
  /api/v1/auth/public/register:
    post:
      operationId: register
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/SignupRequest'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AuthResponse'
          description: Default response
      tags:
      - Register
  /api/v1/auth/public/request-otp:
    post:
      operationId: requestOtp
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/OtpRequest'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OtpRequestResponse'
          description: Default response
      tags:
      - Send custom email verification
  /api/v1/auth/public/validate-email-verification:
    post:
      operationId: validateEmailVerification
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/EmailConfirmationOtpSubmitRequest'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AuthResponse'
          description: Default response
      tags:
      - Validate email verification
components:
  responses:
    "200_0":
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/AuthResponse'
      description: Default response
    "200_1":
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/OtpRequestResponse'
      description: Default response
  schemas:
    array_string:
      items:
        type: string
      type: array
    Role:
      example:
        permissions:
        - roles:
          - null
          - null
          authority: authority
          name: name
          id: id
        - roles:
          - null
          - null
          authority: authority
          name: name
          id: id
        authority: authority
        name: name
        id: id
      properties:
        id:
          type: string
        name:
          type: string
        permissions:
          items:
            $ref: '#/components/schemas/Permission'
          type: array
        authority:
          type: string
      type: object
    array_Role:
      items:
        $ref: '#/components/schemas/Role'
      type: array
    Permission:
      example:
        roles:
        - null
        - null
        authority: authority
        name: name
        id: id
      properties:
        id:
          type: string
        name:
          type: string
        roles:
          items:
            $ref: '#/components/schemas/Role'
          type: array
        authority:
          type: string
      type: object
    array_Permission:
      items:
        $ref: '#/components/schemas/Permission'
      type: array
    ResponseUserDetails:
      example:
        emailVerified: true
        lockedAccount: true
        displayName: displayName
        roles:
        - permissions:
          - roles:
            - null
            - null
            authority: authority
            name: name
            id: id
          - roles:
            - null
            - null
            authority: authority
            name: name
            id: id
          authority: authority
          name: name
          id: id
        - permissions:
          - roles:
            - null
            - null
            authority: authority
            name: name
            id: id
          - roles:
            - null
            - null
            authority: authority
            name: name
            id: id
          authority: authority
          name: name
          id: id
        userId: userId
        deletedAccount: true
        email: email
        username: username
      properties:
        userId:
          type: string
        username:
          type: string
        displayName:
          type: string
        email:
          type: string
        roles:
          items:
            $ref: '#/components/schemas/Role'
          type: array
        emailVerified:
          type: boolean
        lockedAccount:
          type: boolean
        deletedAccount:
          type: boolean
      type: object
    AuthResponse:
      example:
        messages:
        - messages
        - messages
        userDetails:
          emailVerified: true
          lockedAccount: true
          displayName: displayName
          roles:
          - permissions:
            - roles:
              - null
              - null
              authority: authority
              name: name
              id: id
            - roles:
              - null
              - null
              authority: authority
              name: name
              id: id
            authority: authority
            name: name
            id: id
          - permissions:
            - roles:
              - null
              - null
              authority: authority
              name: name
              id: id
            - roles:
              - null
              - null
              authority: authority
              name: name
              id: id
            authority: authority
            name: name
            id: id
          userId: userId
          deletedAccount: true
          email: email
          username: username
        errored: true
        token: token
        refreshToken: refreshToken
      properties:
        errored:
          type: boolean
        messages:
          items:
            type: string
          type: array
        token:
          type: string
        refreshToken:
          type: string
        userDetails:
          $ref: '#/components/schemas/ResponseUserDetails'
      type: object
    SignoutRequest:
      example:
        token: token
      properties:
        token:
          type: string
      type: object
    TokenRefreshRequest:
      example:
        token: token
      properties:
        token:
          type: string
      type: object
    integer_int64:
      format: int64
      type: integer
    deprecated_integer_int32:
      deprecated: true
      format: int32
      type: integer
    Date:
      example:
        date: 1
        seconds: 6
        hours: 5
        month: 5
        year: 7
        timezoneOffset: 3
        minutes: 2
        time: 0
        day: 9
      properties:
        time:
          format: int64
          type: integer
        seconds:
          deprecated: true
          format: int32
          type: integer
        date:
          deprecated: true
          format: int32
          type: integer
        month:
          deprecated: true
          format: int32
          type: integer
        hours:
          deprecated: true
          format: int32
          type: integer
        minutes:
          deprecated: true
          format: int32
          type: integer
        year:
          deprecated: true
          format: int32
          type: integer
        day:
          deprecated: true
          format: int32
          type: integer
        timezoneOffset:
          deprecated: true
          format: int32
          type: integer
      type: object
    OtpRequestResponse:
      example:
        expiryDate:
          date: 1
          seconds: 6
          hours: 5
          month: 5
          year: 7
          timezoneOffset: 3
          minutes: 2
          time: 0
          day: 9
        otpId: otpId
        messages:
        - messages
        - messages
        email: email
        errored: true
      properties:
        errored:
          type: boolean
        messages:
          items:
            type: string
          type: array
        otpId:
          type: string
        email:
          type: string
        expiryDate:
          $ref: '#/components/schemas/Date'
      type: object
    UserDetailsUpdateRequest:
      example:
        password: password
        otpId: otpId
        displayName: displayName
        otpCode: otpCode
        email: email
      properties:
        otpId:
          type: string
        otpCode:
          type: string
        displayName:
          type: string
        email:
          type: string
        password:
          type: string
      type: object
    SigninRequest:
      example:
        emailOrUsername: emailOrUsername
        password: password
      properties:
        emailOrUsername:
          type: string
        password:
          type: string
      type: object
    SignupRequest:
      example:
        password: password
        displayName: displayName
        email: email
        username: username
      properties:
        username:
          type: string
        displayName:
          type: string
        email:
          type: string
        password:
          type: string
      type: object
    OtpRequest:
      example:
        emailOrUsername: emailOrUsername
        message: message
      properties:
        emailOrUsername:
          type: string
        message:
          type: string
      type: object
    EmailConfirmationOtpSubmitRequest:
      example:
        code: code
        otpId: otpId
      properties:
        otpId:
          type: string
        code:
          type: string
      type: object
  securitySchemes:
    Authentication:
      bearerFormat: JWT
      in: header
      scheme: bearer
      type: http
